bootstrap_menu:
  menus:
    main:
      items:
        amateurs:
          label: 'Amateurs'
          route: 'amateurs_list'
        librairies:
          label: 'Jolibrairies'
          route: 'librairies_list'
        genres:
          label: 'Genres'
          route: 'genres_list'
        livres:
          label: 'Livres'
          route: 'livres_list'
        etalage:
          label: 'Etalages'
          route: 'app_etalage_index'
